### ISSUE TITLE
fonction suppression

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#101]
le cursseur disparaît sous les points pleins

**Comment by fredericbonifas** [comment]
Je ne constate pas ce problème, quand est-ce que cela se produit ?

**Comment by mustapha-ija** [comment]
disparait sous les points gris (cercles et fleches)

**Comment by mustapha-ija** [comment]
Version 43.0.2357.130 m

**Comment by fredericbonifas** [comment]
Pas reproduit. À rouvrir si un autre utilisateur constate ce problème
