### ISSUE TITLE
fonction annuler

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#102]
La fonction annuler n'annule que la dernière suppression, pas les autres opérations.
Si ça reste comme ça > la renommer "annuler dernière suppression"

provoque des évènements vraiment curieux. Apparition d'un point à un endroit où il n'y en a jamais eu par exemple. Annuler une opération vraiment antérieure... par exemple

en fait l'annulation de la suppresion d'un point le fait réaparaitre en haut à gauche en plus petit

**Comment by fredericbonifas** [comment]
Je ne constate pas ce problème. Quelles sont les actions qui conduisent à ce problème ?

**Comment by mustapha-ija** [comment]
je n'ai pas renconré le problème depuis, s'il se représente je pourrai t'en dire plus.
