### ISSUE TITLE
Flèches

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#103]
Les faire tourner?
Enlever les flèche verticales une fois qu'on pourra tourner les fleches horizontales.

Visualisation des flèches dans le menu (on ne voit qu'un triangle) pour voir les différences des gabarits.

**Comment by fredericbonifas** [comment]
C'est possible dans la carte locale pour l'instant mais pas à l'étape d'édition.

En attente des décisions de l'issue #138 concernant le menu contextuel d'actions sur les objets
