### ISSUE TITLE
Pouvoir stocker les dessins localement

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#105]
Est il possible de stocker les données en local pour les éditions longues, avec une fonction de récupération ??
la necessité de cette fonction dépend de la fiabilité du système, serveur, navigateur et poste de travail... mais aussi utilisateur, s'il fait une mauvaise manip...

**Comment by mdartic** [comment]
Il est techniquement possible d'utiliser le localStorage du navigateur pour stocker temporairement les données, et uniquement sur le navigateur utilisé.

Le localStorage est une API HTML5 fonctionnant un peu comme une base de données, très légère, permettant de stocker des données pour un site web donné, et ceci dans le navigateur.

A voir si cela correspondrait à la demande exprimée, et à reprioriser...

**Comment by mdartic** [comment]
Je ferme l'issue.

A revoir quand on traitera la bibliothèque en ligne.
