### ISSUE TITLE
présentation du menu d'édition

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#106]
est il possible d'afficher toute la liste des points à sélectionner (menu déroulant 'sélectionnez un style') pour éviter le scrolling dans le tout petit menu déroulant ?

**Comment by fredericbonifas** [comment]
Augmenter la hauteur du menu déroulant est possible, mais si la liste est plus haute que la hauteur de l'écran, il faudra toujours scroller

**Comment by fredericbonifas** [comment]
- [x] Augmenter hauteur
- [x] Texte à côté du symbole
- [x] BBOX du symbole
