### ISSUE TITLE
Transmission d'une édition en cours à la transcription

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#112]
Je ne vois plus le champs qui permettait d'ajouter des commentaires (export au format txt)
Quand le fichier est transmis, quelle est la procédure pour rependre l'édition ?
Faut il passer par "editer un svg" ? et charger le svg ? et la légende ?

**Comment by fredericbonifas** [comment]
Le champ pour renseigner des commentaires est tout en bas, sous la carte et la légende.

Oui il faut pour l'instant passer par "éditer un svg", rien n'est prévu pour la légende pour l'instant
