### ISSUE TITLE
remplissage 'points rapprochés'

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#117]
points rapprochés et points rapprochés 2... c'est la même chose il me semble

**Comment by fredericbonifas** [comment]
Le diamètre des points est légèrement plus élevé pour "points rapprochés 2" : 1.3 au lieu de 1.1

S'il n'y a aucune différence visible pour vous je supprime "points rapprochés 2" ?

**Comment by fredericbonifas** [comment]
Supprimer "points rapprochés 2"
