### ISSUE TITLE
Points gris

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#120]
trop clairs, ça ne gonfle pas, passer sur un gris à 80 ou 90%

> > à tester

**Comment by nathija** [comment]
après test (y compris avec la carte du 5 juin) : ça gonfle vraiment, il vaudrait mieux conserver ce gris pas trop intense 50% pour éviter justement que ces surfaces éclatent si on se rapproche trop du noir. 

du coup le problème semble plutôt être la superposition du gris (et du noir d'ailleurs) sur les couleurs genre rouge, vert?

**Comment by fredericbonifas** [comment]
Y-a-t'il des choses à modifier dans l'éditeur de DER ?

**Comment by fredericbonifas** [comment]
Pour reformuler ma question : dois-je changer la couleur des points gris ?

**Comment by nathija** [comment]
Pour moi toujours pas, c'est la couleur que j'utilise habituellement, ça me va très bien!

**Comment by fredericbonifas** [comment]
Super merci pour ta réponse, je ferme l'issue alors.
