### ISSUE TITLE
Bouton "ajouter POI"

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#122]
Le bouton "ajouter POI" devient "ajouter à la carte" lorsque l'on choisi un poi
au départ c'est une consigne, ensuite ça devient un bouton
garder le bouton ajouter à la carte qui apparait toujours et ajouter une consigne (éventuellement) "choisir ce que vous souhaitez ajouter (ou importer)"

**Comment by fredericbonifas** [comment]
Ajouter un texte à côté du bouton "Ajouter à la carte"

**Comment by fredericbonifas** [comment]
En attente des idées de Bénédicte sur l'ajout de POI au clic mélangé avec l'ajout de POI automatique

**Comment by mdartic** [comment]
modifié par l'appartition d'un bouton 'Ajouter POI' différencié de 'Importer Data OSM'

**Comment by GregIJA** [comment]
Je ne sais plus quelle est la différence entre POI et Data OSM? Dans tous les cas Data OSM n'est pas parlant pour les users.

**Comment by mdartic** [comment]
lié à #254
