### ISSUE TITLE
Ajouter une police noire pour le bigraphisme

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#123]
Arial gras 32 ??
Choix de couleur ? pas noir

**Comment by nathija** [comment]
C'est très gros arial gras 32, ça prend beaucoup de place sur une carte.
Chez nous on va rarement au-delà de 28, la majorité des élèves lisent en 18, et quand on veut une taille "passe-partout" on écrit en 22... Il faut forcément définir une seule taille?

Pour les couleurs, les mêmes que celles du remplissage pour pouvoir varier, sauf noir et gris bien sûr ?

**Comment by fredericbonifas** [comment]
Choix de la taille et de la couleur

**Comment by fredericbonifas** [comment]
@mustapha-ija @nathija On peut maintenant choisir la police et la couleur, est-ce que cela convient ?

**Comment by nathija** [comment]
C'est très bien!
Mais il faudrait plutôt de l'arial gras, si tu peux...
Le braille ne doit pas pouvoir être bleu ou rouge, sinon il ne gonflera pas.
On avait dit que le gros K ne devait pas pouvoir être noir, pour ne pas gonfler (ou précise-le à côté du choix de couleur)?
J'ai un souci pour "viser": quand je tape mon texte il descend d'une ligne par rapport à l'endroit où j'ai cliqué pour insérer la zone de texte, c'est normal ou c'est uniquement chez moi?

**Comment by fredericbonifas** [comment]
@nathija je viens de corriger ces 3 problèmes:
- Arial gras
- choix des couleurs en fonction de braille/pas braille
- décalage vertical du texte

Ça devrait être mieux maintenant :)

**Comment by nathija** [comment]
Presque OK!
Ça bouge toujours verticalement (mais moins peut-être)...
Tu peux afficher du coup dans les choix arial GRAS pour informer les utilisateurs?

**Comment by fredericbonifas** [comment]
Je viens d'ajouter "gras" dans le nom.

Pour les mouvements verticaux du texte ils sont bien plus faible qu'avant. Je ne peux pas pour l'instant travailler sur les décalages de quelques pixels, cela pourra faire l'objet d'une nouvelle issue qui sera traitée s'il reste du temps.
