### ISSUE TITLE
Recueil besoin pour les filtres, zones interactives etc...

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#124]
Une issue pour préparer la discussion plus en détails sur la façon de concevoir le système de filtres et zones intercatives.
L'idée et de poser des questions our y réfléchir avant la discussion.
- quelle taille pour les zones interactivs (taille minimale notemment) ?
- quelles formes possible ?
- renseignement des données point par point sur la carte ou à travers une fenetre qui liste les poi (plus sur un mode tableau où on peux entrer les données à la suite sans avoir à sélectionner les points à chaque fois (peut etre clignotement du point quand on est dans la ligne du tableau ??)
- figurés point automatiquement intercatifs (pour les rues par exemple) ?

and so on...

**Comment by fredericbonifas** [comment]
Traité dans l'issue #91
