### ISSUE TITLE
Déplacement et orientation

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#125]
Il est possible de déplacer les points mais pas les objets. Serait il possible de déplacer les objets ??

**Comment by mustapha-ija** [comment]
polygones : la procédure de déplacement n'est pas suffisemment explicite pour être utilisée quand plusieurs formes sont très proches, on fini par déplacer tout et n'importe quoi

points (flèches etc...) : la fonction déplacer ne prend en compte que les points et il n'est alors pas possible de déplacer la fleche entière ? Supprimer et redessiner ? (déplacer permet de se rendre compte de son encombrement / d'autres formes pour trouver un compromis (ou pas). en supprimant redessinant ça fait faire bcp d'opération pour un simple ajustement. Et il y a souvent des ajustements à faire puisqu'il faut faire cohabiter des éléments tout en s'assurant qu'il soit possible qu'ils soient discriminés tactilement. 

> > (presque doublon avec déplacement des cercles avec une croix)

orientation des fleches : il me semblait qu'il eut été possible de le faire... plus maintenant ??

**Comment by fredericbonifas** [comment]
Corrigé cf Issue #138
