### ISSUE TITLE
déplacement d'éléments créés depuis l'éditeur (dans inkscape)

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#131]
Dans inkscape, lorsque l'on déplace des éléments qui ont été créés dans l'éditeur MC ça crée une ligne
 transform= "translate(valeurs)" ou "matrix(valeurs)" qui n'est apparement pas supportée par le proto.

> > <g
> >      inkscape:groupmode="layer"
> >      id="layer3"
> >      inkscape:label="all from editeur"
> >      style="display:none"
> >      transform="translate(0,-434.62897)">
> >     <g
> >        width="1052.3622875875817"
> >        height="1488.1890935581964"
> >        id="g128-1"
> >        transform="translate(246.79073,-6.6700195)">
> >       <g
> >          class="tiles"
> >          transform="matrix(312.1293,0,0,312.1293,-20602899,-14943106)"
> >          id="g130-8" />

Pour les éléments créés sous inkscape, le problème n'apparait pas pour les translations, mais c'est le cas pour les rotations

> > <rect
> >        style="display:inline;opacity:1;fill:none;fill-opacity:1;stroke:#ff0000;stroke-width:2.77444053;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
> >        id="title"
> >        width="84.917442"
> >        height="81.582428"
> >        x="112.89075"
> >        y="1287.8927"
> >        inkscape:label="#rect6105"
> >        transform="matrix(0.9998477,-0.01745241,0.01745241,0.9998477,0,0)" />

**Comment by GregIJA** [comment]
@fredericbonifas pour moi celle là il faut la clore
le proto ne supportera pas les transformations, mais on résout ça par le biais des bounding box.
A fermer.

**Comment by fredericbonifas** [comment]
Ok pour moi, je ferme
