### ISSUE TITLE
"supprimer ce svg à l'export"

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#132]
dès le départ il s'agit de choisir de supprimer ou non le svg qui sert à dessiner les formes
oui > pour imprimer le DER et le gonfler
non > pour retravailler sur le svg éventuellement, l'avoir affiché sur l'écran (pour travailler sans document gonflé, pourquoi pas ?!)

le mieux serait d'avoir un svg pour l'affichage et la réédition avec le fichier qui sert de modèle
et un fichier qui sert pour l'impression (sous format image, mais ça rejoint d'autres issues #92)

> > mais il est aussi possible d'avoir à imprimer un fichier avec l'image pour les mal voyant (pour le travail avec Anne on a fait 2 versions, une plate et "jolie" pour les mal voyants, une avec des formes simplifiée et gonflée pour les aveugles... mais c'est plutôt P3 là...)

**Comment by fredericbonifas** [comment]
Exporter les deux fichiers:
- uniquement ce qui a été tracé
- ce qui a été tracé + l'image originale
