### ISSUE TITLE
Avoir les boutons d'outils toujours visibles ?

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#157]

**Comment by mdartic** [comment]
changé par la mise en place d'un menu à gauche... c'est un essai, à voir à l'utilisation ?

**Comment by GregIJA** [comment]
Ok sur le principe par contre se pose un vrai problème d'utilisation pour les interactions. On ouvrira d'autres issues si nécessaire.
