### ISSUE TITLE
Création de formes simples

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#177]
Un outil quadrilatère permettant de réaliser des carrés ou rectangles à la dimension souhaitée (INSHEA)

**Comment by nathija** [comment]
rectangle (= carré avec maj ou ctrl) (= parallélogrammes si on peut déformer ?)

**Comment by CeliaP** [comment]
Concernant les formes simples, il seraient intéressant d'avoir : 
- triangles, rectangles, carrés, parallélogrammes
- ce qui peut être envisagé, c'est de générer par ex des carrés à partir des formes rectangles (comme cité au dessus par Nathalie, avec un raccourci clavier maj ou ctrl).

**Comment by mdartic** [comment]
- [x] Dessiner un rectangle
- [x] Lors de l'appui sur shift, dessiner un carré
- [x] Dessiner un triangle
- [x] Permettre la torsion (skew) d'un carré / rectangle pour qu'il devienne losange / parallélogramme
- [x] Lors de la torsion, la limiter à un axe en particulier (X ou Y) en appuyant sur shift

**Comment by mdartic** [comment]
Pour le parallélogramme, je pense qu'il serait plus pertinent de disposer d'une fonction **skew** = torsion de transformation de la forme.

Voici un exemple de ce qu'il serait possible : 
http://www.alsacreations.com/xmedia/tuto/css3/transformations-2d/skewx-skewy.html

Cela permettrait de transformer un rectangle en parallélogramme.

Cette transformation pourrait être appliquée aux autres formes aussi.

A rediscuter ?

**Comment by nathija** [comment]
À quelles formes voudrait-on l'appliquer (à part les carrés pour faire des losanges) ?

Pour les parallélogrammes on pourrait bloquer la transformation sur axe vertical ou horizontal pour éviter de partir en diagonale sans faire exprès, de perdre les mesures de côtés, etc. ?

**Comment by mdartic** [comment]
A quelles formes : je ne sais pas, à toi de me dire si tu vois d'autres cas que carré / rectangle. 
En soi, la transformation de torsion peut être appliquée à n'importe quelle forme.
Si elle n'a pas de sens pour les autres formes que carré / rectangle, on pourra le limiter à ces formes.

Concernant le blocage sur axe X ou Y, je prends note.

**Comment by GregIJA** [comment]
Ok pour toute les formes.
En revanche je ne suis pas sur de l'utilisabilité du skew surtout sans le shift.
On considère ok et on verra à l'usage.

**Comment by mdartic** [comment]
le skew n'est clairement pas optimal.

il pourra avoir une utilité avec l'ajout d'une boîte de dialogue précisant le skewX et le skewY.

et avec une interaction pour le skewX et pour le skewY.

bref, à retravailler, sans souci, mais pas prioritaire.
