### ISSUE TITLE
Vide de confort

### ISSUE THREAD

**Issue by MMace31** [makinacorpus/accessimap-editeur-der#180]
Le vide de confort de 2mm n'apparaît pas autour de la croix. Vérifier pour ts les figurés ?

**Comment by nathija** [comment]
Vide de confort
- dans les formes : intérieur + extérieur
- autour des points d’intérêt (croix, carré) : pas un cercle, plus proche de la forme du figuré, et doit dépasser 2 mm aux extrémités
- extrémités de lignes : 2 mm (et aussi autour des flèches...)

**Comment by mdartic** [comment]
même issue que #182
