### ISSUE TITLE
Vide de confort

### ISSUE THREAD

**Issue by MMace31** [makinacorpus/accessimap-editeur-der#182]
Le vide de confort n'apparaît pas autour des extrémités des lignes

**Comment by CeliaP** [comment]
N'apparaît pas non plus autour des extrémités des 3 points "Croix" et de la "Flèche du Nord".

**Comment by nathija** [comment]
Vide de confort
- dans les formes : intérieur + extérieur
- autour des points d’intérêt (croix, carré) : pas un cercle, plus proche de la forme du figuré, et doit dépasser 2 mm aux extrémités
- extrémités de lignes : 2 mm (et aussi autour des flèches...)

**Comment by mdartic** [comment]
même issue que #180

**Comment by CeliaP** [comment]
![vide_de_confort](https://cloud.githubusercontent.com/assets/18047767/16771904/7817d3ec-4852-11e6-80a2-a805e0e5c9ad.PNG)

**Comment by CeliaP** [comment]
![videconfort_interieur](https://cloud.githubusercontent.com/assets/18047767/17058143/00fc18a2-501f-11e6-8340-8b28fae6f4bd.jpg)

Voici un exemple de vide de confort intérieur.
Il faudrait que le choix des vides de confort intérieur et extérieur soit séparé. Qu'on puisse sélectionner vide de confort extérieur, sans pour autant avoir celui intérieur. 
Sur l'image, on a le vide de confort extérieur fait par l'éditeur, mais également un vide de confort intérieur.
