### ISSUE TITLE
Importer et éditer un SVG pour ajouter des interactions

### ISSUE THREAD

**Issue by MMace31** [makinacorpus/accessimap-editeur-der#185]
Pouvoir copier-coller des éléments d'un SVG existant

**Comment by mdartic** [comment]
semble ok avec l'import désormais, on peut ajouter diverses interactions.
à voir si ok.
(manip : importer un svg au début de la création du document, et éditer le document)

**Comment by CeliaP** [comment]
Export A4 paysage SVG créé à partir de l'éditeur  : ok firefox et ok chrome
Import du même fichier : ok firefox 
  --> MAIS 
[185_sansint.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/357134/185_sansint.zip)
import du fichier svg pas ok pour chrome

**Comment by mdartic** [comment]
peux tu préciser qu'est ce qui n'est pas ok ?

j'ai importé le zip dans firefox et dans chrome, j'ai a priori le même résultat : import ok, un triangle, un carré avec vide de confort, et une ellipse.

**Comment by CeliaP** [comment]
Version 51.0.2704.103 m (64-bit)

**Comment by CeliaP** [comment]
Bug - Ce fichier n'est pas importable avec firefox et chrome
[fleurfruit.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/357206/fleurfruit.zip)

**Comment by mdartic** [comment]
Fix effectué pour l'import de zip sous Chrome / Windows

> peux tu tester ? Je regarde aussi ton nouveau zip

**Comment by CeliaP** [comment]
Cela ne marche pas, on a un message d'erreur "erreur lors de l'import... fichier au mauvais format!... application/x-zip-compressed" pour chrome uniquement

**Comment by mdartic** [comment]
étrange, vu que ça marchait sur firefox juste avant tu m'avais dit ?

concernant le fichier 'fleurfruit.zip', tu importes le zip ou le svg ? car le zip n'est pas au 'format' der (je rajoute un message d'anomalie pour informer l'utilisateur)

et je me rends compte que la fleur n'a pas de 'bordure' comme nous avons en permanence sur tous les dessins.

ne devrait on pas rendre facultatif ce bord noir ? on disait que c'était pour que les DV puissent connaître la fin du dessin, mais pour une fleur c'est inutile non ?

**Comment by CeliaP** [comment]
Non que chrome pardon.
Pour fleurfruit c'est le svg (le zip a été créé pour le mettre sur github).

Pour le message d'erreur pour le zip, j'ai testé le zip créé tout à l'heure avec l'éditeur.

Pour la bordure, faudra qu'on en rediscute avec Nathalie, mais j'avais repris un dessin existant donc je n'ai pas mis de bordure sur le coup.

**Comment by mdartic** [comment]
Tu peux tester à nouveau l'import du fichier ? un fix a été pushé

**Comment by CeliaP** [comment]
Re-testé, ça ne marche pas

**Comment by mdartic** [comment]
concernant cette issue, zip & svg fonctionnent ?

**Comment by GregIJA** [comment]
Oui, en tous cas nos fichiers svg actuels passent. Je clos.
