### ISSUE TITLE
Common map: rétablir la suppression d'un point interactif

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#188]

**Comment by mdartic** [comment]
Use case pour reproduire :
- création d'un POI
- ajout du POI aux interactions
- suppression du POI

Résultat attendu :
- suppression du POI
- suppression de l'interaction

Résultat actuel :
- suppression du POI ok
- pas de suppression de l'interaction

**Comment by mdartic** [comment]
Mistake in the implementation of 'removeObject'.
Was using 'iid' attribute instead of 'data-link' attribute of the POI.

Fixed with commit 7a48943
