### ISSUE TITLE
Interactions - Bounding box

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#189]
Bounding box correctement placée uniquement lorsque le point créé n'a jamais été déplacé (que ce soit avant ou après l'ajout de l’interaction).

**Comment by mdartic** [comment]
Définir les bounding box par typologie de forme

**Comment by mdartic** [comment]
désormais corrigé via l'import d'un dessin déjà réalisé.

cas d'utilisation :
- réalisation d'un der
- export du der
- modification à partir d'inkscape
- réimport dans l'éditeur
- réexport

=> les bounding box sont cohérentes selons les modifications qui ont été effectuées dans l'éditeur

**Comment by mdartic** [comment]
bug #237 déclaré 
lié à la transformation 'déplacer'
