### ISSUE TITLE
Écriture braille

### ISSUE THREAD

**Issue by nathija** [makinacorpus/accessimap-editeur-der#193]
- majuscules, italique... (si possible un caractère séparé pour contrôler l’utilisation, par exemple en maths)
- écriture mathématiques (liste des signes à utiliser + association avec un caractère / code pour les taper)

**Comment by MMace31** [comment]
Manque des infos / besoin d'input sur les polices braille

**Comment by CeliaP** [comment]
Le logiciel ne permet de générer que du texte "littéraire".
Il faudrait que tous les signes braille soient disponibles (une "table" répertoriant tous les symboles) pour pouvoir également contrôler via un raccourci/caractère les signes (mathématiques, etc.).

**Comment by CeliaP** [comment]
Prévoir une réunion IJA sur cette thématique pour clarifier le besoin (voir l'existant/outils utilisés auprès de Nathalie, etc.)

**Comment by fredericbonifas** [comment]
- [x] Ne plus utiliser simbrl
- [x] Laisser une gestion manuelle du "point 6" pour l'écriture mathématique

**Comment by mdartic** [comment]
Réflexion suivante : disposer de légende adaptée aux malvoyants & aveugles = pouvoir écrire en braille & en Arial dans le même mode que le dessin

Deux légendes distinctes au niveau du texte mais commune au niveau de structure (ordre, éléments...)

**Comment by mdartic** [comment]
pour la légende, cf #111

**Comment by CeliaP** [comment]
Est ce que la police "braille 2007" embarquée dans le zip est-elle la bonne ? 
--> voir avec Nathalie

**Comment by mdartic** [comment]
oui, c'est celle qui a été définie lors de la réunion à l'IJA le 17 Mai
