### ISSUE TITLE
Braille : impossible à lire dans SVG avec Inkscape

### ISSUE THREAD

**Issue by nathija** [makinacorpus/accessimap-editeur-der#195]
pb police : la fournir au départ en page accueil ?

**Comment by mdartic** [comment]
J'imagine que tu essaies d'ouvrir le SVG de la légende avec Inkscape, et tu ne dois pas avoir la police installée sur ton poste ?

Si tel est le cas, on peut imaginer 'greffer' la police au zip que tu peux télécharger depuis l'éditeur.

Si tu ne l'as pas sur ton poste, tu pourras ainsi l'installer et Inkscape aura la police nécessaire à l'affichage du SVG.

Qu'en penses tu ?

**Comment by mdartic** [comment]
Validée par Nathalie > on rajoute la police dans le zip
