### ISSUE TITLE
Possibilité de mettre couleur sur le fond de carte

### ISSUE THREAD

**Issue by nathija** [makinacorpus/accessimap-editeur-der#197]

**Comment by mdartic** [comment]
bug #229

**Comment by CeliaP** [comment]
Ok chrome + firefox  pour les couleurs en fond (configurer le fond)
Mais : lorsqu'on laisse fond uni comme choix pour trame de fond, et qu'on sélectionne ensuite une couleur cela ne marche pas (il faut changer de fond -ex : hachures- puis rechoisir fond uni)

**Comment by mdartic** [comment]
semble ok de mon côté suite à changement de la profondeur du calque (#229)

**Comment by CeliaP** [comment]
Ok pour chrome aussi

**Comment by mdartic** [comment]
=> je te laisse fermer l'issue.
