### ISSUE TITLE
Surcharge RAM sous Chrome (duplicate 203)

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#201]
Après l'ajout des points d'intérêts, dans le mode édition, difficulté pour supprimer les figurés (routes, etc.)

**Comment by mdartic** [comment]
Est ce que tu peux qualifier les 'difficultés' rencontrées ?

**Comment by CeliaP** [comment]
Lorsqu'on édite une carte avec la carte locale, qu'on choisit de mettre les éléments (places, bâtiments, routes etc.), puis qu'ensuite on passe dans le mode édition, on rencontre des difficultés pour supprimer certains éléments (une route, une place, etc.) : 
-> au bout de quelques éléments supprimés (4 généralement, en attendant un peu, un 5ème peut être supprimé, et puis ça ne marche plus), malgré que l'on clique sur la "poubelle", l'élément "clignote" mais ne disparaît pas.
->  d'autres fois, je ne pouvais même pas faire apparaître le moyen de supprimer les éléments, mais je pense que cela est dû à la fuite mémoire, car en fermant le navigateur, cela a fonctionné de nouveau.

**Comment by mdartic** [comment]
ok, merci pour tes précisions.

pourrais tu me préciser encore le 'niveau de zoom' que tu utilises.

car, à mon niveau, quand je rajoute les bâtiments, il y a une grande complexification des calculs, liée au nombre de bâtiments.
=> ce qui explique que le pc va commencer à galérer pour traiter tous ces éléments...

j'ai pas encore testé avec la suppression de certains bâtiments, je vais voir si il y a une optimisation possible à ce niveau là.

néanmoins, je me dis que afficher autant de bâtiment en simultané provoquera toujours une saturation de calcul + mémoire du navigateur... chrome, firefox, peu importe.

lié au bug #203

**Comment by CeliaP** [comment]
Je peux te donner les points de départ et d'arrivée que j'ai utilisé généralement : 
- 37 rue monplaisir Toulouse à Museum Toulouse
- 37 rue monplaisir Toulouse à Place Esquirol Toulouse
- 37 rue monplaisir Toulouse à Place du Capitole Toulouse
  La carte s'affiche donc avec ces deux points, elle est centrée pour qu'on est les deux, donc je ne touche plus au zoom.

Je viens de tester de nouveau la carte locale en utilisant comme point de départ toujours l'IJA et en point d'arrivé Place du Capitole. J'ai mis que quelques éléments : les routes principales, les passages piétons et les parcs. Dans le mode édition, tu arrives à supprimer des éléments mais au bout de 4 ça commence à être plus compliqué, càd que soit le menu ne s'affiche plus, il faut patienter un peu, soit l'élément ne se supprime pas, il faut donc réessayer.

**Comment by mdartic** [comment]
Grand merci pour tes précisions, elles vont bien m'aider.

Stay tuned !

**Comment by CeliaP** [comment]
De rien ! Bon courage

**Comment by mdartic** [comment]
Test effectué sur Firefox, Chrome, mais pas de souci...
Tu es sur quel navigateur ? 
Est ce que tu saurais me dire la configuration de ton poste : RAM par exemple...

**Comment by CeliaP** [comment]
Sur Chrome.
Si je ne me trompe pas : 
Mémoire installée RAM : 4,00 Go (3.87 utilisable)
Processeur Intel(R) Core(TM) i7-4510 U CPU

**Comment by GregIJA** [comment]
On ferme, pas reproduit.
