### ISSUE TITLE
Gérer le réimport d'un DER créé via l'éditeur.

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#202]

**Comment by mdartic** [comment]
Bonjour Grég,

Si tu as des anomalies précises que tu as déjà rencontré, merci de les préciser pour les cibler en priorité.

**Comment by mdartic** [comment]
Grég, est ce que tu peux me dire si cette issue est liée à la #163 ?

**Comment by GregIJA** [comment]
J'ai fais pas mal de test.
L'un d'eux pose problème.
Je dessine un rond que je déplace. Puis j'exporte. 
![202_1_export](https://cloud.githubusercontent.com/assets/12393758/19601670/92207274-97aa-11e6-9660-9bc4d49983ab.JPG)
J'obtiens ce zip
[202_1.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/544515/202_1.zip)

Je retourne sur la page principale et je vide de cache (important!). Je clic sur "créer un nouveau DER".
J'importe.
![202_1_import](https://cloud.githubusercontent.com/assets/12393758/19601868/4a857364-97ab-11e6-8933-c434fb1ee919.JPG)
Le rond (ou tout autre objet) est décalé.

**Comment by mdartic** [comment]
lié à #260
