### ISSUE TITLE
Pouvoir ajouter une image dans le dessin

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#207]
Par exemple, comme pour le DER de Londres.

**Comment by mdartic** [comment]
- [x] Importer l'image dans le dessin
- [x] Exporter l'image dans l'export du DER
- [x] Importer l'image à partir du DER
- [ ] Ajouter l'image dans les patterns pour réutilisation par url en cas de duplication

**Comment by mdartic** [comment]
isolation du dernier point dans une autre issue en cas d'utilité (non prioritaire pour l'instant)

**Comment by CeliaP** [comment]
[207.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/357114/207.zip)

Importer l'image dans le dessin (Contexte mozilla/chrome; A4 paysage car en A3 paysage on ne peut éditer) : 
- png et jpeg ok
- svg ok mais une question : j'ai un fichier svg (A3 - dessiné au départ avec l'éditeur v1), qui est vraiment petit dans le dessin lorsqu'il est importé, à quoi cela est du ?

**Comment by mdartic** [comment]
le svg qui est dans le zip a une dimension de 420x297 (width / height), 

il est importé avec cette dimension...
