### ISSUE TITLE
Pouvoir sélectionner le fond de carte (OSM, MapBox)

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#210]
Les tuiles OSM permettent de voir beaucoup plus de POIs que Mapbox streets

**Comment by mdartic** [comment]
Je vais rajouter un sélecteur de fond de carte :
- fond de carte OSM
- font MapBox Streets
- autres ? (à voir plus tard)

**Comment by mdartic** [comment]
Prévoir aussi l'impact sur l'import / export pour retrouver l'état de l'export :
- [x] ajouter un groupe de layer
- [x] ajouter fond OSM
- [x] ajouter l'information du fond de carte utilisé dans le fichier d'export
- [x] importer correctement le fond de carte utilisé, avec une valeur par défaut si inexistant ?

**Comment by fredericbonifas** [comment]
En attente de la résolution du bug #219 pour tester complètement.
