### ISSUE TITLE
Changement de style d'un POI non fonctionnel

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#211]
Après ajout d'un point en mode carte, le changement de style d'un POI ne fonctionne pas (j'ai l'impression que le style change mais pas la forme)

**Comment by fredericbonifas** [comment]
Ça ne fonctionne toujours pas après ajour d'un point en mode carte.

**Comment by mdartic** [comment]
ok, je regarde ça à nouveau et le fixe... à nouveau
