### ISSUE TITLE
Le comportement 'blink' des features n'est pas toujours cohérent

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#217]
Je propose de changer la 'sélection active' par un liseré d'une couleur à définir (bleu, rouge, ...), et revoir la gestion de cet état en CSS.

Je referais une passe pour que la gestion de cette classe (ajoutée / retirée) soit cohérente. (par exemple, lorsque l'on déplace un item, il ne doit pas être en train de clignoter)

**Comment by GregIJA** [comment]
Ok pour le liseré rouge sur le principe. On a pas testé tous les objets.
