### ISSUE TITLE
Pas d'icône du sélecteur de fond de plan

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#221]

**Comment by mdartic** [comment]
est ce que tu peux décrire ce que tu entends pas 'sélecteur de fond de plan' ?

**Comment by fredericbonifas** [comment]
En mode Carte, c'est le bouton en haut à droite qui permet de choisir le fond Mapbox Street ou OSM

**Comment by mdartic** [comment]
... ben oui.
c'est pas comme si on en avait parlé tout à l'heure...
:'(
