### ISSUE TITLE
Bug lors de l'ajout de POI

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#227]
Parfois, après plusieurs manipulations du dessin, lorsqu'on veut à nouveau ajouter un POI, il n'y a plus la recherche du POI...

Creuser dans la gestion des modes de dessins

**Comment by mdartic** [comment]
Ok, problème d'initialisation des modes.

**Comment by GregIJA** [comment]
Pas reproduit.
