### ISSUE TITLE
Interactions : suppression d'un point interactif

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#234]
Scénario
Création d'un dessin + ajout d'un point interactif
Le point est bien dans les points interactifs
Retour sur le dessin et suppression de ce point
Le point est toujours dans la liste des points interactifs (et du coup toujours dans le xml).

**Comment by mdartic** [comment]
- [ ] supprimer l'interaction d'un POI lors de la suppression du POI

**Comment by mdartic** [comment]
La suppression de l'interaction est désormais intégrée.
A valider.
