### ISSUE TITLE
Interactions : impossible de créer des objets après import d'un svg

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#235]
Scénario (Firefox+Chrome)
Import d'un svg (je le met en fichier attaché)
Impossible ensuite de créer des objets (cercle, carré, points etc.)
[london.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/357293/london.zip)

**Comment by GregIJA** [comment]
C'est ok pour ce point mais j'ai une question avant de fermer.
J'ai créé un svg en A4 portait depuis Inkscape.
Je l'importe en A4 portrait dans l'éditeur et il semble bcp trop grand.

[dessin.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/544577/dessin.zip)
(obligé de le zipper on peut pas glisser directement un svg)

**Comment by mdartic** [comment]
Pour ma part,
J'arrive à importer le svg, mais il n'est pas importé au bon endroit par rapport au dessin.
=> fix à réaliser.
Je laisse cette issue fermée (puisque tu m'as indiqué que ct ok de ton côté) mais j'en ouvre une autre au sujet que tu évoques.
