### ISSUE TITLE
Export de DER

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#236]
Scénario (Firefox+Chrome) A4 paysage
Import de DER avec svg (en copie)
Export de ce DER : l'export de finit jamais
[london.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/357321/london.zip)

**Comment by mdartic** [comment]
a priori, lors de l'import du SVG, il faut supprimer les metadata (ajoutées par inkscape) qui casse l'export

**Comment by mdartic** [comment]
- [ ] lors de l'import d'un svg / zip, supprimer les metadata

**Comment by GregIJA** [comment]
Ca marche pour ce zip en particulier.
En revanche j''ai fait un dessin tout simple en Inkscape. 
[dessin.zip](https://github.com/makinacorpus/accessimap-editeur-der/files/544598/dessin.zip)
J'ai importé le svg et j'ai exporté.
Message d'erreur suivant 
<img width="960" alt="236" src="https://cloud.githubusercontent.com/assets/12393758/19602714/95135664-97ae-11e6-8442-78cedb573802.png">

**Comment by mdartic** [comment]
Ok, à reproduire de mon côté et à corriger en v1.

**Comment by mdartic** [comment]
lié à #260
