### ISSUE TITLE
Interaction : déplacement d'un POI

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#237]
Scenario 
Création d'un point "petit cercle vide", rajout d'interaction.
Déplacement de ce point. L'interaction ne suit pas --> sur le fichier xml mêmes coordonnées qu'avant le déplacement.

**Comment by mdartic** [comment]
Effectivement,

Souci au niveau de l'action du déplacement
- [ ] Changer les coordonnées x / y du feature déplacé
