### ISSUE TITLE
Menu contextuel

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#238]
![bugmenucontextuel](https://cloud.githubusercontent.com/assets/18047767/16769573/940199ca-4849-11e6-991d-036908b9c322.jpg)
![bugmenucontextuel_2](https://cloud.githubusercontent.com/assets/18047767/16769574/940454ee-4849-11e6-90c5-0c941a85745f.jpg)

Test Mozilla + Chrome
Création d'une figure. On clique sur le menu contextuel qui est de taille normale. Lorsqu'on zoome et qu'on reclique sur le menu contextel : 
le menu devient tout petit (après zoom sur figure) ou énorme (après dézoom sur figure)
Dans tous les cas, le zoom devrait garder une taille normal -taille verrouillée-

**Comment by GregIJA** [comment]
ok
