### ISSUE TITLE
Perte de la transformation après copie / déplacement

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#239]
Création d'un triangle ou d'un carré
Application d'une transformation
Si je copie ou déplace l'objet transformé, je retrouve ma forme d'origine

**Comment by mdartic** [comment]
Je n'ai pas réussi à reproduire cette anomalie.

**Comment by GregIJA** [comment]
Je viens de la reproduire sous Firefox.
<img width="343" alt="copie" src="https://cloud.githubusercontent.com/assets/12393758/23308148/73efa7c6-faaa-11e6-8be6-9fb4b80a53d4.PNG">

Je crée un triangle et j'y applique une transformation. Ce devient le triangle de gauche.
Je copie ce triangle. Il devient le triangle de droite : la transformation n'a pas été conservée.

**Comment by bastyen** [comment]
La perte de transformation est-elle toujours d'actualité ?
Je n'arrive pas à la reproduire pour ma part.

1. Création d'un triangle
2. Application d'une rotation
3. Copie du triangle
4. Le nouveau triangle applique bien la transformation

**Comment by GregIJA** [comment]
Pour la rotation oui ça marche depuis longtemps, mais pas pour la transformation (je sais pas comment la nommer) qui est dans le menu contextuel au dessus du copier.
Ceci dit cette fonction n'est pas vraiment utilisable! J'aurais tendance à la supprimer tout simplement.
Qu'en pense @mdartic ?

**Comment by bastyen** [comment]
Ok, je confirme, cette transformation 'spécial' est perdu dans ce cas là.

**Comment by mdartic** [comment]
Oui c'est la fonction `skew` (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform)

Est ce que la transformation `translation` est bien gérée ?

Si oui, alors on peut clore l'issue, et @BastienAlvez tu pourras supprimer la fonction `skew` dans une autre issue ?

**Comment by bastyen** [comment]
De quel translation parle-tu ?
De plus, si on supprime l'option, je comprend pas pourquoi on doit gérer une quelconque translation

**Comment by mdartic** [comment]
Vu à l'oral, on peut clore l'issue et ouvrir une autre pour la suppression du `skew`.
