### ISSUE TITLE
Lignes droites

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#241]
Régression par rapport à la V1
Avec ctrl on pouvait créer des lignes droites, cela n'est plus possible dans la v2

**Comment by mdartic** [comment]
Je n'ai pas constaté ce fonctionnement sur http://makinacorpus.github.io/accessimap-editeur-der/v1/#/commonmap ?

Quand je clique sur 'Ligne', maintient la touche Ctrl, je n'ai aucune modification ?

**Comment by mdartic** [comment]
vu avec Fréd, il y a un angle à respecter => effectivement il y a régression

**Comment by mdartic** [comment]
- [ ] intégrer mécanique Ctrl > ligne droite

**Comment by mdartic** [comment]
lié à #268
