### ISSUE TITLE
Quand je fais une recherche d'adresses, des points sont positionnées sur la carte et la carte se centre automatiquement

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#242]
Impossible de faire fonctionner la carte : si je met une adresse de départ (et d'arrivée) j'ai une erreur 
TypeError : EditService.FitBounds is not a function
Firefox & Chrome

**Comment by mdartic** [comment]
- [x] Fixer la recherche d'adresse
- [x] Maintenir les objets créés à seulement un startPoint et un stopPoint
- [x] Centrer automatiquement la carte sur les adresses recherchées
- [x] Appeler startPoint 'point de départ' et stopPoint 'point d'arrivée'

**Comment by mdartic** [comment]
Déployé sur github.io, à vérifier.

**Comment by GregIJA** [comment]
Je n'ai plus d'erreur et les points sont correctement ajoutés mais il me semble que ce n'est toujours pas le comportement de la V1 : la carte se centre automatiquement de telle sorte à voir directement dans le cadre le point de départ et d'arrivée. Peux tu reboucler avec Fred. Moi je demande à Anna et/ou Nath.
Autre chose : dans le listing des éléments, essayons au maximum de mettre des termes en français (startPoint et stopPoint).

**Comment by mdartic** [comment]
Ok. 
Tu as raison, la carte doit se centrer.
Je rajoute un item à faire.

**Comment by bastyen** [comment]
C'est maintenant corrigé

**Comment by GregIJA** [comment]
Sous chrome, la carte ne se centre pas plus (que je mette une seule adresse ou deux d'ailleurs).
Jeu de test : 
départ : 37 rue monplaisir, Toulouse
arrivée : 6 rue Claude Nougaro, sainte foy d'aigrefeuille

**Comment by mdartic** [comment]
Déploiement effectué
@GregIJA tu peux tester ?

**Comment by GregIJA** [comment]
Toujours pas.
J'ai même une régression puisque quand je tape les adresses les POIs n'apparaissent plus.

**Comment by GregIJA** [comment]
Plus de précision : si je tape par exemple 37 rue monplaisir, toulouse la console me donne

```
vendor-b0f85d629d.js:23735 TypeError: Cannot read property 'color' of undefined
    at drawFeature (app-ba16368ce8.js:5621)
    at LayerGeoJSONService.drawAddress (app-ba16368ce8.js:5537)
    at app-ba16368ce8.js:8864
    at processQueue (vendor-b0f85d629d.js:26198)
    at vendor-b0f85d629d.js:26214
    at Scope.$eval (vendor-b0f85d629d.js:27497)
    at Scope.$digest (vendor-b0f85d629d.js:27310)
    at Scope.$apply (vendor-b0f85d629d.js:27605)
    at done (vendor-b0f85d629d.js:21646)
    at completeRequest (vendor-b0f85d629d.js:21848)
```

**Comment by bastyen** [comment]
C'est ok maintenant, problème de fusion.

**Comment by GregIJA** [comment]
Yes it is.
