### ISSUE TITLE
Interactions : impossible de supprimer les filtres

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#243]
Tout est dans le titre.

**Comment by GregIJA** [comment]
La suppression marche mais des choses ne sont pas fonctionnelles:
- [x] lorsque je n'ai plus de filtres, le bouton "Créer un nouveau Filtre" n'est plus visible,
- [x] si je crée un filtre "Test", puis au autre "Test2"; je supprime "Test" : il m'est impossible de recréer le filtre "Test"

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. 
Repeater: filter in $ctrl.interactions.getFilters() track by filter.id, Duplicate key: f3, Duplicate value: {"id":"f3","name":"Test","gesture":"tap","protocol":"tts"}
```
- [x] bonus : lorsque je clic sur Créer filtre ce serait bien de vider les champs du formulaire de création et de fermer le formulaire

**Comment by GregIJA** [comment]
@mdartic la correction ne semble pas être en prod?

**Comment by mdartic** [comment]
exact, le build n'a pas été ok :
https://travis-ci.org/makinacorpus/accessimap-editeur-der/builds/173889234

les modifs vont plus profond que ce que l'on pensait. @BastienAlvez est dessus.

**Comment by GregIJA** [comment]
Ok
