### ISSUE TITLE
Changement de couleur de fond pour objets

### ISSUE THREAD

**Issue by CeliaP** [makinacorpus/accessimap-editeur-der#245]
Lorsqu'on crée un objet, qu'on sélectionne la palette de couleur pour changer la couleur de fond de l'objet, on a le changement lorsqu'on clique une 1ère fois mais ensuite ça ne se change plus. Il faut fermer la fenêtre et cliquer de nouveau sur la palette de couleur.
--> sous chrome - création d'un triangle : je sélectionne la palette de couleur à partir du menu éditer, je choisis rouge (sans fermer la fenetre) mais je change d'avis je veux du vert (le changement ne s'opère pas, il faut fermer la fenêtre "palette de couleur" pour pouvoir de nouveau sélectionner vert et que le changement s'opère.

**Comment by GregIJA** [comment]
Ok.
