### ISSUE TITLE
Menu contextuel "persistent"

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#250]
Si j'affiche le menu contextuel d'un objet, ce menu ne disparait pas tant que je ne choisi pas d'action.
Je propose de faire disparaître le menu soit quand on choisi une action (comportement actuel) mais aussi qd on perd le focus de l'objet. C'est du P3 mais peut être facile à régler.

**Comment by mdartic** [comment]
Ok, je l'ajoute au projet v1.

**Comment by GregIJA** [comment]
Ok.
