### ISSUE TITLE
Interactions sur tous les objets

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#251]
Je suis étonné de ne pas avoir trouvé cette issue mais on en a parlé plus d'une fois à l'oral.
L'interaction doit être possible sur tous les éléments du dessin et pas spécifiquement les POIs, ce d'autant plus que le futur lecteur saura le faire proprement. Je dirai P2 mais pour moi à mettre dans la V1.0.

**Comment by mdartic** [comment]
related to #267
