### ISSUE TITLE
Filtre OSM

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#253]
Il me semble que le filtre OSM créé par défaut pollue les esprits pour les novices (et les autres aussi).
Je pense du coup à 2 choses :
1 - Le filtre Valeur OSM n'est créé que si on a récupéré au moins une fois des POI OSM. Je n'ai aucune idée de la complexité de cette demande.
2 - Le nom du filtre est a changé pour qu'il soit plus parlant. Une idée?

**Comment by mdartic** [comment]
Vu avec Greg,
=> changement du nom par 'Défaut'
=> le filtre n'est pas créé à la volée
