### ISSUE TITLE
Menu contextuel en premier plan

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#257]
Le menu contextuel ne s'ouvre pas en tout premier plan ce qui fait qu'en majorité du temps certaines actions sont cachées pour les objets créés trop près du bord du cadre.

**Comment by mdartic** [comment]
Modification du comportement à tester :
- affichage au dessus des calques
- conservation de la bonne taille d'affichage peu importe le niveau de zoom
- affichage à l'endroit du clic

=> à tester

**Comment by GregIJA** [comment]
Je laisse cette issue ouverte car le menu contextuel n'est pas encore utilisable : 
Je suis sous Chrome & Win 10.
Si je crée un figuré en bas à droite de mon dessin et que je fais appel au menu contextuel, j'ai juste un tout petit bout du menu qui apparait.

**Comment by GregIJA** [comment]
<img width="667" alt="capture" src="https://cloud.githubusercontent.com/assets/12393758/20891142/d2c1a56e-bb09-11e6-81d2-585f279ef120.PNG">

**Comment by GregIJA** [comment]
Le bug existe toujours sous Chrome.

**Comment by bastyen** [comment]
Le menu apparait bien au bon endroit sur Chrome et Firefox pour ma part.
J'ai un léger écart lorsque le debugger de Chrome est ouvert, et intégré à la page, je pense pas que ce cas (de dev) soit à prendre en compte ?

**Comment by GregIJA** [comment]
Le problème de décalage sous chrome apparaît si le texte Windows n'est pas à 100% (par défaut sous win10 on est à 150%).
On clos mais dans la doc bien préciser que sous chrome ne fonctionne que sous cette condition.
