### ISSUE TITLE
Lorsque j'importe un fond, je ne dois pas pouvoir le sélectionner avec le mode éditer du dessin

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#259]
Si j'importe une image SVG dans l'éditeur,
Que je vais dans le mode dessin,
Que je sélectionne le bouton 'éditer' 
Que je clique droit sur le fond, 
J'ai la roue crantée qui apparaît...
=> ça ne devrait pas !
=> fixer l'anomalie.

**Comment by mdartic** [comment]
@GregIJA, je me posais la question de la pertinence de mon avis...

Est ce que justement ce n'est pas 'pratique' de pouvoir éditer le fond du dessin malgré tout ?

**Comment by GregIJA** [comment]
A mon avis j'aurais tendance à dire qu'on doit être capable de l'éditer à tout moment aussi.

**Comment by mdartic** [comment]
Ok

Je ferme cette issue et on laisse l'édition active.
