### ISSUE TITLE
Changer le bouton importer en 'Ouvrir'

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#262]
- [x] Conserver le style d'un bouton 'classique'
- [ ] Changer le libellé en Ouvrir (bouton type file => bouton classique)
- [x] Prévoir une zone plus accessible

**Comment by GregIJA** [comment]
Finalement je vois que importer a été conservé. On clos cette issue on verra bien les retours utilisateurs.

**Comment by mdartic** [comment]
Arg, oui, j'ai remis Importer, car Cindy n'a pas eu le réflexe de passer par 'Ouvrir' mais par 'Télécharger' pour importer un document... :'(
