### ISSUE TITLE
L'affichage sur les navigateurs web sur Windows 10 est trop gros

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#264]
L'affichage n'est pas à la bonne échelle.

A voir s'il manque des meta pour fixer le width ou la scale.

**Comment by mdartic** [comment]
En fait, c'est le niveau de zoom de Windows 10 qui est configuré à 150%...

=> Paramètres > Système > Affichage 

Régler la taille du texte à 100%

Appliquer, 
et voilà...

@GregIJA tu pourras tester demain ?

Si c'est ok pour toi, je rajouterais un petit texte quelque part pour expliquer la manipulation sur Windows.

**Comment by GregIJA** [comment]
Ça marche!
125% suffit pour voir le tout.
