### ISSUE TITLE
Régression : sous Firefox & Chrome la carte ne s'affiche plus

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-editeur-der#284]

**Comment by mdartic** [comment]
mmm, en fait, c'est les tuiles de mapbox qui ne s'affichent plus.

Celles d'OSM fonctionnent bien.

On a un souci de token a priori.

A traiter.

**Comment by GregIJA** [comment]
ok c'est pas bien grave ...

**Comment by mdartic** [comment]
non, je vais mettre par défaut les tuiles d'osm dans un premier temps.

**Comment by mdartic** [comment]
Bon, au final j'ai changé le token de mapbox.

A voir si cela suffit (il faut attendre le build pour pouvoir le constater)

**Comment by mdartic** [comment]
Non, ça ne suffit pas, je mets OSM par défaut.
