### ISSUE TITLE
MapSense

### ISSUE THREAD

**Issue by thomasbonnier** [makinacorpus/accessimap-editeur-der#290]
Bonjour, 

Je fait un stage d'ergonomie sur MapSense avec l'IRIT. Pour l'instant je crée les cartes sous Inkscape puis j'édite les interactions sur le XML.
J'aimerais sur des cartes avoir plusieurs niveaux de complexité (plusieurs cartes physiques, pour un seul fichier SVG, les interactions de chaque carte sont dans un filtre différent). Mais certains POI vont donc être présent sur plusieurs des cartes. Je n'arrive pas à trouver la formule qui fonctionne (qui ne fait pas planter MapSense), si c'est finalement possible, pour attribuer plusieurs filtres à un même POI (que le POI soit actif pour chaque menu de l'interface dans lequel il a été inscrit)

J'espère être assez clair

quelqu'un aurait-il une réponse à me fournir ?

Merci d'avance

**Comment by mdartic** [comment]
Bonjour @thomasbonnier ,
J'ai besoin de plus de précisions.
Déjà, combien de temps dure ton stage ? Quelle période plus exactement ?
Quand tu parles de MapSense, tu parles du lecteur fait par l'IRIT ou celui qui est disponible sur makinacorpus/accessimap-lecteur-der ?
Est ce qu'il est vraiment indispensable que tu aies tout dans un seul DER interactif ?
Car, à mon sens, tu essaies de mettre dans un même DER interactif plusieurs DER physiques... Cela ne me paraît pas vraiment être une bonne idée ?

Ce que tu peux faire, c'est au niveau d'un même DER physique, et de son alter ego numérique, tu peux définir plusieurs filtres. Un qui serait un son, l'autre le nom du POI, l'autre une explication plus précise, et ainsi de suite.

Mais peut être je n'ai pas bien compris ta demande.

**Comment by thomasbonnier** [comment]
bonjour,

Mon stage se déroule au CIVAL Lestrade, établissement de l'ASEI accueillant
des perosnnes déficientes visuelles. C'est un stage d'ergonomie, je travail
davantage sur la conception des usages liés au dispositif. J'utilise le
programme développé par l'IRIT. J'édite en SVG les cartes sous inkscape,
puis code les interactions via les ID désignées dans le SVG sur un fichier
XML du même nom placé dans le même répertoire.
Mais mon problème a été réglé, grâce à l'aide de Marc Macé, mon encadrant à
l'IRIT. En fait, je désirais, pour une utilisation du dispositif dans un
cadre rééducatif ou d'apprentissage, permettre plusieurs niveaux de
complexité des cartes. c'est à dire plusieurs filtres représentant chacun
un niveau de complexité, avec des POI qui lui sont propres et d'autres qui
sont présents sur plusieurs filtres.  Je cherchais donc comment dans le
fichier XML, le traduire pour que ce soit reconnu par le programme. J'ai
donc réussi, en recopiant la ligne <action> du POI changeant le nom du
filtre dans lequel je veux que celui-ci soit actif. Je l'ai testé et cela
foncitonne. Parallèlement à cela, je devrai imprimer chaque carte physique
en thermoformé représentant chacune un niveau de complexité.

Merci tout de même de votre réponse.

cordialement

thomas BONNIER

Thomas Bonnier


Le 2 juin 2017 à 10:23, Mathieu DARTIGUES <notifications@github.com> a
écrit :
