### ISSUE TITLE
Améliorer la définition des interactions

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-editeur-der#296]
* permettre une définition plus centralisée pour les filtres / interactions
* ajouter un contrôle visuel sur les interactions déjà définies

**Comment by MedHediAmri** [comment]
Définition plus centralisée des filtres et contrôle visuel sur les interactions déjà définies: OK.
Par contre, je n'arrive pas à accéder à la valeur de l'interaction. On ne peut pas insérer un texte devant "Défaut" par exemple pour donner une valeur.

**Comment by lellex** [comment]
La valeur de défaut peut être changée dans l'onglet interaction, dans "Types d'interactions (filtres)"

**Comment by MedHediAmri** [comment]
C'est vrai dans le cas d'un seul filtre qui est le premier par défaut. Mais quand on ajoute une autre interaction les champs associés aux valeurs sont désactivés et on ne peut pas insérer des textes.

**Comment by MedHediAmri** [comment]
Test effectué. Bug corrigé.
