### ISSUE TITLE
Zoom trop grand --> fond blanc

### ISSUE THREAD

**Issue by jouffrais** [makinacorpus/accessimap-editeur-der#37]
J'utilise Firefox 37.0.2

**Comment by mdartic** [comment]
Ce bug semble apparaître uniquement sur Firefox, et plutôt lié à la bibliothèque d3 elle même... 
Le téléchargement des tuiles s'effectue correctement, mais l'affichage par d3 pose souci, a priori avec le facteur zoom de transformation de la tuile.
Pas de solution de contournement pour l'instant.

**Comment by mdartic** [comment]
Corrigé par l'utilisation de leafletJS normalement. à confirmer.

**Comment by GregIJA** [comment]
OK. A noter que l'on met de côté pour le moment les issues liées à Firefox.

**Comment by mdartic** [comment]
Tu confirmes quand même que le bug n'apparaît plus ?
J'ai le doute quand tu dis 'on met de côté les issues liées à Firefox'.
Certes, c'en était une, mais normalement l'anomalie est corrigé.
Je te laisse clôturer l'issue en fonction de ton retour.

**Comment by GregIJA** [comment]
Oui oui lorsque je le met à done considère que c'est corrigé.
Tu veux que je clos les issues quand elles sont ok pour moi?

**Comment by mdartic** [comment]
Si ça te dérange pas, oui :-)
