### ISSUE TITLE
Aggregate specific POI extracted from open data repositories

### ISSUE THREAD

**Issue by grdenis** [makinacorpus/accessimap-editeur-der#45]
Exemple des feux sonores.
Ceux ci sont dispo en Open Data depuis le repo de Toulouse Métropole
https://data.toulouse-metropole.fr/les-donnees/-/opendata/card/21703-carrefours-feux-sonores
Dispo en csv et json ...
J'ai fais un tour rapide sur Toulouse Métropole et je n'ai rien trouvé d'autre.

**Comment by fredericbonifas** [comment]
À importer sur OSM et gérer comme les autres POIs
