### ISSUE TITLE
Possibilité d'ajouter une image de fond

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#67]
- [ ] Pouvoir la positionner
- [ ] Pouvoir changer son échelle

**Comment by nathija** [comment]
Est-ce que, au moment de l'exportation, l'image de fond pourrait être sur un calque séparé? J'ai testé avec un de mes fichiers SVG pour décalquer et à la fin tout est sur le même plan. Du coup ce sera fastidieux de trier les éléments du SVG "image de fond" sans abimer le DER décalqué.

**Comment by fredericbonifas** [comment]
@nathija j'ai mis cela en place : en partant d'un svg, cocher la case "Supprimer ce SVG à l'export final".
Est-ce que cela convient ?

**Comment by nathija** [comment]
Oui! (Pour les étourdis tu peux rajouter qu'il faut cocher la case avant de sélectionner le fichier? Ou mettre le choix à la fin, au moment de l'exportation...)

Pourrait-on aussi utiliser des jpeg ou des pdf, pour les fichiers scannés?

**Comment by fredericbonifas** [comment]
"N'exporter que les éléments ajoutés"
