### ISSUE TITLE
Couleur des flèches

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#69]
Grises pour toutes les flèches (correspondant au gris 50% dans inkscape)
Avec des trames de fond pour les plus grosses flèches.

**Comment by fredericbonifas** [comment]
Les flèches sont maintenant en gris.

Quelle doit être la trame à utiliser pour les plus grosses flèches ?

**Comment by nathija** [comment]
Une trame sans contour, petites hachures 45, et une avec contour, petits points mais pas trop légers.

**Comment by fredericbonifas** [comment]
Voici les flèches que j'ai ajoutées est-ce qu'elles conviennent ?
![selection_111](https://cloud.githubusercontent.com/assets/1278216/7882668/2d32eaae-0610-11e5-885f-28a6a1edf0ea.png)

**Comment by fredericbonifas** [comment]
Et @nathija ça fait plaisir de te voir sur Github :)

**Comment by nathija** [comment]
Elles correspondent à la commande, je les testerai au four lundi pour vérifier.

**Comment by nathija** [comment]
Flèches passées au four, ça sort très bien. En revanche je ne parviens pas à les orienter comme je veux, comment faut-il faire pour qu'elles tournent?

**Comment by fredericbonifas** [comment]
Elles tournent sur la carte locale. En mode édition ça va venir, cf issue #103
