### ISSUE TITLE
bug ajout de 'toutes les rues'

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#71]
à l'ajout de traits parallèles sur toutes les routes ça crée des problèmes (graves) sur la carte.
![carte_bug](https://cloud.githubusercontent.com/assets/12170174/7936827/524afa64-093c-11e5-8ce6-4214751e68c0.jpg)

**Comment by fredericbonifas** [comment]
Merci pour le retour, ce devrait être corrigé
