### ISSUE TITLE
Recherche d'adresse : ajouter un marqueur temporaire

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#73]

**Comment by fredericbonifas** [comment]
2 champs de recherche d'adresse pour départ et arrivée. A la recherche, zoom sur la zone

**Comment by mustapha-ija** [comment]
a.  Laisser les repères de point de départ et arrivée pendant l’édition qui partiront avec la carte au moment de l’export

**Comment by fredericbonifas** [comment]
duplicate #81
