### ISSUE TITLE
Affichage du nom des rues dans le svg, supprimer a l'export

### ISSUE THREAD

**Issue by fredericbonifas** [makinacorpus/accessimap-editeur-der#78]

**Comment by fredericbonifas** [comment]
@mustapha-ija @nathija : j'ai ajouté le nom des rues au survol avec la souris, comme montré dans l'image ci-dessous. Est-ce que ça conviendrait ?
![selection_113](https://cloud.githubusercontent.com/assets/1278216/8009215/6ed46cf2-0ba7-11e5-891d-7a9725b418d4.png)

**Comment by nathija** [comment]
Je viens de tester et comme c'est moins agressif que cette étiquette noire (j'ai vu une petite info-bulle beige) ça me parait bien.
