### ISSUE TITLE
Symbole d'orientation du document

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#83]
Pour orienter la carte sur l’écran il faut un symbole normé qui soit interactif. L’interaction déclenche la lecture du titre. Le symbole doit être orientable (tous les 90°). Il représente un angle et est placé dans un angle (il suit l’angle du document) (cf doc png, le svg n'est pas supporté). (18*18mm)
![symbole de positionnement du document](https://cloud.githubusercontent.com/assets/12170174/8063201/bba6c33e-0ed3-11e5-8f25-7ec4db65f0c5.png)

**Comment by fredericbonifas** [comment]
Ajouter dans la liste des points un symbole "flèche du Nord"
