### ISSUE TITLE
Ajouter cercles pleins de blanc

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#89]
pour servir à placer les figurés sans être confondus avec la trame de fond

**Comment by mustapha-ija** [comment]
rajouter comme pour les polygones du fond blanc en option 
plus vide de confort en option

**Comment by fredericbonifas** [comment]
Le vide de confort doit être de la couleur du polygone en-dessous

**Comment by fredericbonifas** [comment]
Les points actuellement sans remplissage doivent être remplis de blanc.
