### ISSUE TITLE
Le menu doit être toujours visible pour réduire le scrolling

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#90]
Peut être aussi mettre un menu en deux parties, une en haut, l'autre sur le coté gauche... à réfléchir

**Comment by fredericbonifas** [comment]
Duplicate #56

**Comment by fredericbonifas** [comment]
Menu du haut toujours visible

**Comment by fredericbonifas** [comment]
Problème corrigé, cela pourra être revu lors d'une réorganisation plus globale
