### ISSUE TITLE
Améliorer la création des interactions

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#91]
à retravailler avec les utilisateur et Grégoire pour définir les objectifs et contraintes
en lien avec #124

**Comment by GregIJA** [comment]
@fredericbonifas 

En mode édition :
- [x] il est possible d'afficher ou de faire disparaître (par défaut) un panneau latéral dans lequel:
- [x] affichage d'un tableau : POIs en ligne et filtres en colonnes
- [x] chaque colonne représente un filtre (son "id" non éditable, "nom" du filtre éditable et "guidage" valeur oui ou non, éditable, par défaut non) 
- [x] chaque ligne représente un POI (son "id")
- [x] par défaut 2 filtres sont créés = "Aucune Interaction" avec guidage à "non", et "Valeur OSM" avec guidage à "non".
- [ ] Dans chaque case au croisement d'un POI et d'un filtre on peut éditer une valeur et un protocole = tts ou mp3 par défaut tts)
- [x] il est possible de supprimer ou d'ajouter un filtre
- [x] il est possible de supprimer un POI (donc une ligne du tableau) 
- [x] quand je sélectionne un POI depuis mon svg et que je le rend interactif, il est automatiquement ajouté à mon tableau et la ligne associée est mise en surbrillance
- [x] fenêtre de confirmation si suppression d'un élément interactif depuis la carte
- [x] la valeur OSM doit être renseignée quand elle existe
- [x] largeur du tableau adaptée
- [x] icônes explicites pour ouvrir/fermer le panneau de définition des filtres

| id | f0 | f1 | f2 |
| --- | --- | --- | --- |
| **name** | **Aucune interaction** | **Valeur OSM** | **Type de magasin** |
| **guidage** | **non** | **non** | **oui** |
| title | Carte des commerces |  |  |
| poi1 |  | Coiffeur x | Salon de coiffure |
| poi2 |  | Petit Casino | Epicerie |

**Comment by fredericbonifas** [comment]
@GregIJA cela convient-il ?

**Comment by GregIJA** [comment]
@fredericbonifas super boulot 
quelques remarques / ajouts
- dans la colonne id remplacer name par "nom", Guidage par "guidage?", title par "titre"
- par défaut le guidage est à faux pour le filtre OSM
- il manque à implémenter 
  "Dans chaque case au croisement d'un POI et d'un filtre on peut éditer une valeur et un protocole = tts ou mp3 par défaut tts)"

Et je rajoute les demandes suivantes:
- Dans chaque case au croisement d'un POI et d'un filtre on peut éditer une valeur, un protocole = tts ou mp3 par défaut tts ET un geste (click, double click ou appuie long, double click par défaut)
  (cf #50 pour impact fichier xml)
- si on choisit le protocole mp3 il faut être capable de sélectionner un fichier mp3 depuis un explorateur de fichier, de mettre le nom du fichier en tant que valeur de l'action et d'intégrer le fichier mp3 dans le zip généré.

**Comment by GregIJA** [comment]
@fredericbonifas
petite modification du fichier xml
une action possède un attribut supplémentaire "gesture" qui prends une des valeurs single_tap, double_tap ou long_tap. (cf la spec #91)

**Comment by mdartic** [comment]
Suite à démo hier, il faut pouvoir customiser la 'gesture' par interaction, et non par catégorie.

**Comment by mdartic** [comment]
@GregIJA 

une nouvelle façon a été implémentée pour les interactions.

pourrais tu nous faire un retour d'utilisabilité ?

**Comment by GregIJA** [comment]
Il y a un problème d'utilisabilité avec le fonctionnement actuel. On doit souvent faire des aller retour entre Interactions et Dessin. On approche de quelque chose de bien mais on a encore des choses à revoir pour que ce soit plus intuitif.

Exemple : si j'ai 2 points interactifs, quand je suis dans le menu Interactions il m'est impossible de savoir qui est poi-1 et poi-2. Il faudrait au moins prévoir un feedback visuel.

Est-ce que Bénédicte peut vous aider sur le sujet?
Est-ce que le menu Interactions ne peut pas apparaître dès lors que je rend un point interactif?

**Comment by mdartic** [comment]
Effectivement, la visualisation du 'poi' courant est au programme. On va l'intégrer sur ce ticket.

Concernant les aller retours, c'est pas optimisé, c'est clair... une réflexion est en cours.

Pour l'apparition immédiatement après avoir rendu un point interactif, pas sûr.

Mais peut être l'ajout des interactions sur les items uniquement quand tu es en édition des interactions, et pas en mode 'édition' dessin.

A suivre

**Comment by mdartic** [comment]
- [ ] Visualiser le point d'interaction en concordance avec l'édition des valeurs des interactions
- [ ] Permettre l'ajout des interactions directement depuis le mode 'interaction'

**Comment by GregIJA** [comment]
C'est déjà bien mieux!
Je crois qu'on tient quelque chose là.
Et les propriétés des objets éditables en live c'est très prometteur.
Cool.
