### ISSUE TITLE
Impression du document

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#92]
Exporter une image pour impression ou imprimer directement (étape à retravailler avec les utilisateurs, Grégoire et Marc éventuellement, pour définir les objectifs et contraintes)

**Comment by fredericbonifas** [comment]
Exports:
- SVG : dessin
- SVG : source + dessin
- PDF : dessin
- PDF : source + dessin

**Comment by mustapha-ija** [comment]
nomenclature des noms de fichiers à déterminer

**Comment by fredericbonifas** [comment]
Duplicate #132
