### ISSUE TITLE
Import de documents à utiliser comme fond

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#93]
quels formats sont importables ?
Lesquels devraient être importables ?

**Comment by nathija** [comment]
Pour faire hyper simple (et éviter de forcer les pauvres utilisateurs à utiliser des logiciels pour convertir etc) on pourrait avoir comme format ce qui sort du scan par défaut, PDF ou JPEG?

**Comment by mustapha-ija** [comment]
Import de pdf et image ?? voir ensuite si c'est utilisable ou pas et comment c'est améliorable

**Comment by fredericbonifas** [comment]
http://stackoverflow.com/questions/1554280/extract-text-from-pdf-in-javascript#answer-20522307

**Comment by fredericbonifas** [comment]
@nathija Il est maintenant possible d'importer des PDF, JPG ou PNG !
Merci de tes retours :)

**Comment by nathija** [comment]
Je ne parviens pas à importer les PDF...
Et je ne sais pas comment tourner mon image PNG ou la redimensionner dans l'éditeur de DER.

**Comment by fredericbonifas** [comment]
Merci pour ce retour @nathija 

Pourrais-tu stp m'envoyer par mail le PDF qui pose problème ?

Pour la rotation/redimensionnement d'une image ce n'est pas encore possible. Si c'est vraiment nécessaire, il faudra qu'on voie ensemble quelles fonctionnalités sont utiles et comment les intégrer
