### ISSUE TITLE
Marge

### ISSUE THREAD

**Issue by mustapha-ija** [makinacorpus/accessimap-editeur-der#99]
C'est possible de la rendre impossible à supprimer ? mais je me demande si c'est vraiment utile

ça laisse plus de flexibilité à l'utilisateur mais s'il supprime la marge, n'annule pas faute d'avoir compris, faudra tout recommencer.

**Comment by nathija** [comment]
Utile surtout en A3 puisqu'on ne peut pas faire gonfler les bordures de feuilles donc mieux vaut une marge qui empêche de compter dessus

**Comment by mustapha-ija** [comment]
la même question se pose pour la fonction déplacer

Nathalie dit : ni suppression si déplacement
